/* Generated by Yosys 0.57+263 (git sha1 da2e021e3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module avsddac(clk, reset, RV_TO_DAC_bits, OUT);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [9:0] RV_TO_DAC_bits;
  wire [9:0] RV_TO_DAC_bits;
  output [9:0] OUT;
  wire [9:0] OUT;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$101 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$103 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$105 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$107 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$109 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$111 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$93 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$95 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$97 ;
  wire \$abc$112$auto$rtlil.cc:3372:NotGate$99 ;
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$113  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$93 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$114  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$95 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$115  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$97 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$116  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$99 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$117  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$101 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$118  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$103 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$119  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$105 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$120  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$107 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$121  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$109 )
  );
  sky130_fd_sc_hd__clkinv_1 \$abc$112$auto$blifparse.cc:397:parse_blif$122  (
    .A(reset),
    .Y(\$abc$112$auto$rtlil.cc:3372:NotGate$111 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$80  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[0]),
    .Q(OUT[0]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$93 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$81  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[1]),
    .Q(OUT[1]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$95 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$82  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[2]),
    .Q(OUT[2]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$97 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$83  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[3]),
    .Q(OUT[3]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$99 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$84  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[4]),
    .Q(OUT[4]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$101 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$85  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[5]),
    .Q(OUT[5]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$103 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$86  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[6]),
    .Q(OUT[6]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$105 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$87  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[7]),
    .Q(OUT[7]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$107 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$88  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[8]),
    .Q(OUT[8]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$109 )
  );
  sky130_fd_sc_hd__dfrtp_1 \$auto$ff.cc:266:slice$89  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[9]),
    .Q(OUT[9]),
    .RESET_B(\$abc$112$auto$rtlil.cc:3372:NotGate$111 )
  );
endmodule

module vsdbabysoc(clk, reset, OUT);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output [9:0] OUT;
  wire [9:0] OUT;
  wire [9:0] RV_TO_DAC_bits;
  avsddac u_dac (
    .OUT(OUT),
    .RV_TO_DAC_bits(10'hxxx),
    .clk(clk),
    .reset(reset)
  );
  assign RV_TO_DAC_bits = 10'hxxx;
endmodule
