/* Generated by Yosys 0.57+263 (git sha1 da2e021e3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module avsddac(clk, reset, RV_TO_DAC_bits, OUT);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [9:0] RV_TO_DAC_bits;
  wire [9:0] RV_TO_DAC_bits;
  output [9:0] OUT;
  wire [9:0] OUT;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_101 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_103 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_105 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_107 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_109 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_111 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_93 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_95 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_97 ;
  wire _abc_112_auto_rtlil_cc_3372_NotGate_99 ;
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_113  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_93 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_114  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_95 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_115  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_97 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_116  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_99 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_117  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_101 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_118  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_103 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_119  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_105 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_120  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_107 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_121  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_109 )
  );
  sky130_fd_sc_hd_clkinv_1 _abc_112_auto_blifparse_cc_397_parse_blif_122  (
    .A(reset),
    .Y(_abc_112_auto_rtlil_cc_3372_NotGate_111 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_80  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[0]),
    .Q(OUT[0]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_93 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_81  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[1]),
    .Q(OUT[1]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_95 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_82  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[2]),
    .Q(OUT[2]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_97 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_83  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[3]),
    .Q(OUT[3]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_99 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_84  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[4]),
    .Q(OUT[4]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_101 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_85  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[5]),
    .Q(OUT[5]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_103 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_86  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[6]),
    .Q(OUT[6]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_105 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_87  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[7]),
    .Q(OUT[7]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_107 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_88  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[8]),
    .Q(OUT[8]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_109 )
  );
  sky130_fd_sc_hd_dfrtp_1 _auto_ff_cc_266_slice_89  (
    .CLK(clk),
    .D(RV_TO_DAC_bits[9]),
    .Q(OUT[9]),
    .RESET_B(_abc_112_auto_rtlil_cc_3372_NotGate_111 )
  );
endmodule

module vsdbabysoc(clk, reset, OUT);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output [9:0] OUT;
  wire [9:0] OUT;
  wire [9:0] RV_TO_DAC_bits;
  avsddac u_dac (
    .OUT(OUT),
    .RV_TO_DAC_bits(10'hxxx),
    .clk(clk),
    .reset(reset)
  );
  assign RV_TO_DAC_bits = 10'hxxx;
endmodule
